language: java

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key: ${api_key}
  file:
    - target/kafka-connect-http-plugin-${project_version}.jar
    - target/kafka-connect-http-plugin-${project_version}-javadoc.jar
    - target/kafka-connect-http-plugin-${project_version}-sources.jar
    - target/kafka-connect-http-plugin-${project_version}-package.tar.gz
  skip_cleanup: true
  on:
    tags: true
  name: ${project_version}
