# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Release to GitHub

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github

      - name: Install gpg secret key
        run: echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Release Prepare
        run: mvn -B release:prepare
      - name: Release Perform
        run: mvn -B release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
